export const SET_ITEMS = "SET_ITEMS";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const ADD_PRESSED = "ADD_PRESSED";
export const DELETE_PRESSED = "DELETE_PRESSED";
export const UPDATE_PRESSED = "UPDATE_PRESSED";
export const SET_COLLECTION_SELECT = "SET_COLLECTION_SELECT";
